<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>3.0.0</VersionPrefix>
    <Description>A library enabling typed routing in ASP.NET Core MVC projects. Next generation of the Strathweb.TypedRouting Web API 2 library.</Description>
    <Authors>filipw</Authors>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Strathweb.TypedRouting.AspNetCore</AssemblyName>
    <PackageId>Strathweb.TypedRouting.AspNetCore</PackageId>
    <PackageTags>ASP.NET Core;routing;typed;asp net;aspnetcore</PackageTags>
    <PackageIcon>strathweb.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/filipw/Strathweb.TypedRouting.AspNetCore</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/filipw/Strathweb.TypedRouting.AspNetCore.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\strathweb.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
